server:
  port: 8081
  servlet:
    session:
      cookie:
        name: UISESSIONMEMBER
security:
  oauth2:
    client:
      client-id: drug
      client-secret: 123
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
    resource:
      user-info-uri: http://localhost:8080/user/me
      token-info-uri: http://localhost:8080/oauth/check_token
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///medicine?serverTimezone=UTC
    password: 123456
    username: root
